### ISSUE TITLE
Installation instructions issue

### ISSUE THREAD

**Issue by savage-ren** [HHS/ckanext-datajson#13]
I'm having issues with the installation instructions.  I followed the instructions located at https://github.com/HHS/ckanext-datajson.

When I try to restart apache2 and hit the ckan server, I get the following error stack in the log file:

[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1] mod_wsgi (pid=2683): Target WSGI script '/etc/ckan/default/apache.wsgi' cannot be loaded as Python module.
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1] mod_wsgi (pid=2683): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1] Traceback (most recent call last):
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]   File "/etc/ckan/default/apache.wsgi", line 5, in <module>
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]     from paste.deploy import loadapp
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/**init**.py", line 3, in <module>
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]     from paste.deploy.loadwsgi import *
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 8, in <module>
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]     import pkg_resources
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2727, in <module>
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]     add_activation_listener(lambda dist: dist.activate())
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 700, in subscribe
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]     callback(dist)
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2727, in <lambda>
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]     add_activation_listener(lambda dist: dist.activate())
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2230, in activate
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]     map(declare_namespace, self._get_metadata('namespace_packages.txt'))
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1827, in declare_namespace
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]     _handle_ns(packageName, path_item)
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1797, in _handle_ns
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]     loader.load_module(packageName); module.__path__ = path
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]   File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]     mod = imp.load_module(fullname, self.file, self.filename, self.etc)
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]   File "/usr/lib/ckan/default/src/ckanext-datajson/ckanext/datajson/**init**.py", line 9, in <module>
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]     from plugin import DataJsonPlugin
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]   File "/usr/lib/ckan/default/src/ckanext-datajson/ckanext/datajson/plugin.py", line 1, in <module>
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]     import ckan.plugins as p
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/**init**.py", line 5, in <module>
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]     import toolkit as _toolkit
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/toolkit.py", line 4, in <module>
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1]     import paste.deploy.converters as converters
[Mon Sep 29 07:46:19 2014] [error] [client 127.0.0.1] AttributeError: 'module' object has no attribute 'deploy'

There is a blurb in the steps that imply that there may be a python dependency issue with wsgi and instructs the user to do the following:

“If you're running CKAN via WSGI, we found a strange Python dependency bug. It might only affect development environments. The fix was to revise wsgi.py and add:

import ckanext
before
from paste.deploy import loadapp”

I couldn't find this wsgi.py that had this "...paste.deploy..." line, but I did find the apache.wsgi file that was located in /etc/default/ckan/.  I added the import line but I still get the same issue.  Are there steps in the installation instructions that are missing.  I'm not familiar with python but it does seem like this is a dependency issue.  Would you be able to point me in the right direction.

**Comment by zr2d2** [comment]
It looks like your ckanext-datajson source code isn't installed inside your virtual environment. I believe it should be installed inside the `src` directory of your CKAN virtual environment. Also, I believe this has only been tested with CKAN 2.0.1, so you may have to modify the extension to work with more modern versions of CKAN

**Comment by savage-ren** [comment]
Zach,

It looks like your ckanext-datajson source code isn't installed inside your
virtual environment. I believe it should be installed inside the src directory
of your CKAN virtual environment.

*I'm not sure what you mean by this.  When you say CKAN virtual
environment, do you mean the step where I have to run the activate script
to be in the python environment?  Do I have to be inside a certain folder
(src?) to run *

pip install -e git+
https://github.com/HHS/ckanext-datajson.git#egg=ckanext-datajson

I believe this has only been tested with CKAN 2.0.1, so you may have to
modify the extension to work with more modern versions of CKAN

_How do you modify the extension to work with modern versions of CKAN?_

_Thank you so much for all your help!_

_Renato Guevara_
