### ISSUE TITLE
 PluginNotFoundException: datajson

### ISSUE THREAD

**Issue by Atharex** [HHS/ckanext-datajson#18]
I followed your instructions to install this extension (yes, I used my python virtualenv).

After adding the datajson plugin to my ckan.ini and running python setup.py develop, my ckan install
broke (latest stable release - v 2.4.0), and also execution of any python scripts in the virtualenv.

_The apache log states:_
[Mon Aug 24 09:40:07.653795 2015] [:error] [pid 9593] [remote 127.0.0.1:6647] mod_wsgi (pid=9593): Target WSGI script '/etc/ckan/default/apache.wsgi' cannot be loaded as Python module.
[Mon Aug 24 09:40:07.653851 2015] [:error] [pid 9593] [remote 127.0.0.1:6647] mod_wsgi (pid=9593): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Mon Aug 24 09:40:07.653875 2015] [:error] [pid 9593] [remote 127.0.0.1:6647] Traceback (most recent call last):
[Mon Aug 24 09:40:07.653894 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]   File "/etc/ckan/default/apache.wsgi", line 10, in <module>
[Mon Aug 24 09:40:07.653956 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]     application = loadapp('config:%s' % config_filepath)
[Mon Aug 24 09:40:07.653969 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Mon Aug 24 09:40:07.654119 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]     return loadobj(APP, uri, name=name, *_kw)
[Mon Aug 24 09:40:07.654131 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
[Mon Aug 24 09:40:07.654147 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]     return context.create()
[Mon Aug 24 09:40:07.654157 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
[Mon Aug 24 09:40:07.654170 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]     return self.object_type.invoke(self)
[Mon Aug 24 09:40:07.654179 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 146, in invoke
[Mon Aug 24 09:40:07.654191 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]     return fix_call(context.object, context.global_conf, *_context.local_conf)
[Mon Aug 24 09:40:07.654199 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]   File "/usr/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
[Mon Aug 24 09:40:07.654241 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]     val = callable(_args, *_kw)
[Mon Aug 24 09:40:07.654263 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware.py", line 58, in make_app
[Mon Aug 24 09:40:07.654364 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]     load_environment(conf, app_conf)
[Mon Aug 24 09:40:07.654375 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]   File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 232, in load_environment
[Mon Aug 24 09:40:07.654476 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]     p.load_all(config)
[Mon Aug 24 09:40:07.654487 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 134, in load_all
[Mon Aug 24 09:40:07.654554 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]     load(*plugins)
[Mon Aug 24 09:40:07.654564 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 148, in load
[Mon Aug 24 09:40:07.654578 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]     service = _get_service(plugin)
[Mon Aug 24 09:40:07.654586 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 255, in _get_service
[Mon Aug 24 09:40:07.654598 2015] [:error] [pid 9593] [remote 127.0.0.1:6647]     raise PluginNotFoundException(plugin_name)
[Mon Aug 24 09:40:07.654613 2015] [:error] [pid 9593] [remote 127.0.0.1:6647] PluginNotFoundException: datajson

_Executing any python script after installing this extension hangs up (more specifically after running python setup.py develop) and shows this trace after interrupting it (only in the virtualenv, otherwise python works normally):_
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup, find_packages
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/setuptools/**init**.py", line 11, in <module>
    from setuptools.extension import Extension
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/setuptools/extension.py", line 5, in <module>
    from setuptools.dist import _get_unpatched
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/setuptools/dist.py", line 16, in <module>
    import pkg_resources
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources.py", line 2736, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources.py", line 698, in subscribe
    callback(dist)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources.py", line 2736, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources.py", line 2274, in activate
    list(map(declare_namespace, self._get_metadata('namespace_packages.txt')))
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources.py", line 1882, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources.py", line 1849, in _handle_ns
    loader.load_module(packageName)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/vid/ckan-extensions/ckanext-datajson/ckanext/datajson/__init__.py", line 9, in <module>
    from plugin import DataJsonPlugin
  File "/home/vid/ckan-extensions/ckanext-datajson/ckanext/datajson/plugin.py", line 14, in <module>
    from package_to_pod import make_datajson_entry, get_facet_fields
  File "/home/vid/ckan-extensions/ckanext-datajson/ckanext/datajson/package_to_pod.py", line 3, in <module>
    import validator
  File "/home/vid/ckan-extensions/ckanext-datajson/ckanext/datajson/validator.py", line 28, in <module>
    for row in csv.DictReader(urllib.urlopen("https://raw.github.com/seanherron/OMB-Agency-Bureau-and-Treasury-Codes/master/omb-agency-bureau-treasury-codes.csv")):
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 437, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1178, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 562, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt

Why does python break after installing this extension? Is there a way to make it work and how?

Thank you!

**Comment by medined** [comment]
Do your environment have access to download the csv file from raw.github.com?
